baseURL = "https://mariarzv.github.io/"
languageCode = "en-us"
title = "Maria Razzhivina"
theme = "PaperMod"

[params.profileMode]
  author = "Maria Razzhivina"
  description = "AI Research and Consulting"
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowShareButtons = false
  disableSpecial1stPost = true
  disableScrollToTop = false
  hideSummary = true
  disableAnchoredHeadings = true
  ShowPostNavLinks = false

  profileMode = true
  profileModeTitle = "Maria Razzhivina"
  profileModeSubtitle = "AI Research and Consulting"
  profileModeImage = "images/avatar.png"

  ShowCodeCopyButtons = true

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"

[[menu.main]]
  identifier = "publications"
  name = "Publications"
  url = "/publications/"

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"

[[menu.main]]
  identifier = "news"
  name = "News"
  url = "/news/"

[params.assets]
  css = ["css/custom.css"]